#! /usr/bin/python
import os
import sys

with open("./paths", 'r') as paths_read:
    paths = paths_read.read().split("\n")

with open("./custom", 'r') as custom_read:
    custom = custom_read.read().split("\n")

selection = input("Push OR Pull: ")
print("------------------------------------------")

def copy_files(options):
    for path in paths:
        if path == "":
            break
        if path[-1] == "/":
            print("Flolder: ", path)
            os.system("cp -rf " + options[0] + path + '* ' + options[1] + path)
        else:
            print("File: ", path)
            os.system("cp -f " + options[0] + path + ' ' + options[1] + path)
    print("------------------------------------------")

def remove_custom():
    for file in custom:
        if file == "":
            break
        print("Custom File: ", file)
        os.system("rm ./" + file)

if selection == "Push" or selection == "push":
    options = ['~/.', './']
    copy_files(options)
    remove_custom()
    os.system("git init && git add . && git commit -m 'Update' && git push")
    print("------------------------------------------")
    print("Push: Done.")
elif selection == "Pull" or selection == 'pull':
    options = ['./', '~/.']
    os.system("git pull")
    remove_custom()
    copy_files(options)
    os.system("./customize")
    print("------------------------------------------")
    print("Pull: Done.")
else:
    print("Invalid Input")
    sys.exit()
